Multitenancy support
aion-dk/dbas pull request #10
Opened 2022-09-05 11:37 UTC by 4lgn

- A feature update to support multitenancy architecture, making it possible to programmatically change the URL that the Verifier Client (js-client) uses.
- Updates to the existing automated tests to support multitenancy
- Updates to the documentation regarding multitenancy

2022-09-07 11:13 UTC, av-lukas requested changes

2022-09-07 11:22 UTC, av-lukas commented on README.md
> +To support multitenancy, allowing the client to support multiple different boards by changing the URL routes, we have a couple of helpers to manage the shared `AVVerifier` throughout the app (initial
This project doesn't exercise the `AVVerifier` but rather the `AVClient`.

2022-09-07 11:38 UTC, av-lukas commented on src/constants.ts
> +  process.env.REACT_APP_FALLBACK_BOARD_SLUG || 'us'
We've had conversations about having a global registry containing publicly available election boards that would be used as a fallback. This would act as the defacto fallback by having DBAS & VMB display a dialog asking the user which election they'd like to interact with...scenes from next week's episode :smile:

2022-09-08 08:16 UTC, av-lukas approved these changes

2022-09-19 09:11 UTC, av-alexander commented on src/constants.ts
> +  process.env.REACT_APP_FALLBACK_BOARD_SLUG || 'us'
I agree that there should not be a fallback, when talking final product. I suspect that adding the fallback board url is to ensure nothing will break for those who  are used to using the DBAS/VMB services by simply booting them up.

I think the error screen showing if no board could be loaded will suffice.

2022-09-19 09:12 UTC, av-alexander approved these changes

2022-09-19 09:14 UTC, av-alexander approved these changes

2022-09-19 12:31 UTC, merged